### ISSUE TITLE
58w和58E

### ISSUE THREAD

**Issue by songdf666** [nyaang/GraduationInternship#13]
尊敬的作者您好，很感谢您的开源项目让我学到很多关于数据分析的知识，但是在学习过程中我碰到几个疑问，您有空的时候能帮忙解答一下吗，万分感谢！
我已经跑出58.csv的数据，发现后面预测和分析与58W.csv和58Ecvs有关，请问这两个文件该如何得到呀

**Comment by nyaang** [comment]
DATA目录下有提供啊
